### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by RIMQ** [SpitefulFox/Avaritia#40]
When I open the Neuton Collector GUI and then SHIFT+LEFT CLICK the item, it dupes it until it reaches 64 Items.
It's like the bug with "Fossils and Archeology Revival" Analyzer Bloc

**Comment by SpitefulFox** [comment]
This is what I get for calling the Fossils author a noob for that glitch. >.>

**Comment by RIMQ** [comment]
someone said that this is already fixed but not on curse... any idea when will it be fixed in Avaritia?

**Comment by SpitefulFox** [comment]
That person was probably talking about Fossils and Archaeology mod.  It's not fixed yet.  It'll get fixed when I fix it.
